# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "endpoint", # <dose_response>
  ".data", # <effect>
  "window.start", # <effect>
  "window.end", # <effect>
  "scenario", # <effect>
  "ep", # <epx_binary_search>
  "level", # <epx_binary_search>
  "mf", # <epx_binary_search>
  "gridExtra", # <derive_range>
  ".data", # <derive_range>
  ".", # <format_table>
  "scenario", # <pull_metadata>
  "context", # <pull_metadata>
  "tag", # <set_param_multi>
  "model", # <set_param_multi>
  "name", # <set_param_multi>
  "desc", # <set_param_multi>
  NULL
))
