# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "endpoint", # <dose_response>
  ".data", # <effect>
  "window.start", # <effect>
  "window.end", # <effect>
  "scenario", # <effect>
  "endpoint", # <epx_min_win>
  "level", # <epx_min_win>
  "EPx", # <epx_min_win>
  "window.start", # <epx_min_win>
  "size", # <epx_min_win>
  "ep", # <epx_binary_search>
  "level", # <epx_binary_search>
  "mf", # <epx_binary_search>
  "time", # <derive_range>
  "trial", # <derive_range>
  "FrondNo", # <derive_range>
  "data", # <derive_range>
  "gridExtra", # <derive_range>
  "V1", # <extract_focus_profile>
  "V2", # <extract_focus_profile>
  "V3", # <extract_focus_profile>
  "DateTime", # <extract_focus_profile>
  ".", # <format_table>
  "trial", # <plot_sd>
  "time", # <plot_ppc>
  "trial", # <plot_ppc>
  "obs", # <plot_ppc_combi>
  "pred", # <plot_ppc_combi>
  "study", # <plot_ppc_combi>
  "min", # <plot_ppc_combi>
  "max", # <plot_ppc_combi>
  "EPx", # <plot_epx>
  "len", # <plot_epx>
  "scenario", # <pull_metadata>
  "context", # <pull_metadata>
  "tag", # <set_param_multi>
  "model", # <set_param_multi>
  "name", # <set_param_multi>
  "desc", # <set_param_multi>
  NULL
))
